# Generated by Django 4.2.14 on 2024-08-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.PositiveSmallIntegerField(choices=[(30, 'Half an hour'), (60, 'An hour'), (120, 'Two hours')], verbose_name='Продолжительность (в мин.)')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='doctors.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='services.service')),
            ],
            options={
                'verbose_name': 'опция услуги',
                'verbose_name_plural': 'Опции услуги',
            },
        ),
    ]
