# Generated by Django 4.2.14 on 2024-08-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 минут'), (60, '1 час'), (120, '2 часа')], verbose_name='Продолжительность (в мин.)'),
        ),
    ]
