# Generated by Django 4.2.14 on 2024-08-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveSmallIntegerField(choices=[(30, 'Half an hour'), (60, 'An hour')], verbose_name='Продолжительность (в мин.)'),
        ),
    ]
