# Generated by Django 4.2.14 on 2024-08-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('service', 'price'), 'verbose_name': 'опция услуги', 'verbose_name_plural': 'Опции услуги'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('specialization',), 'verbose_name': 'услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
