# Generated by Django 4.2.14 on 2024-08-20 10:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseschedule',
            options={'verbose_name': 'расписание дня клиники', 'verbose_name_plural': 'Расписание клиники'},
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'verbose_name': 'расписание дня доктора', 'verbose_name_plural': 'Расписание доктора'},
        ),
        migrations.AlterModelOptions(
            name='exceptioncase',
            options={'verbose_name': 'исключение', 'verbose_name_plural': 'Исключения'},
        ),
        migrations.AlterField(
            model_name='baseschedule',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(0, 0), '0:00'), (datetime.time(1, 0), '1:00'), (datetime.time(2, 0), '2:00'), (datetime.time(3, 0), '3:00'), (datetime.time(4, 0), '4:00'), (datetime.time(5, 0), '5:00'), (datetime.time(6, 0), '6:00'), (datetime.time(7, 0), '7:00'), (datetime.time(8, 0), '8:00'), (datetime.time(9, 0), '9:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00'), (datetime.time(23, 0), '23:00')], null=True, verbose_name='Конец рабочего дня'),
        ),
        migrations.AlterField(
            model_name='baseschedule',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Открыто'),
        ),
        migrations.AlterField(
            model_name='baseschedule',
            name='start_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(0, 0), '0:00'), (datetime.time(1, 0), '1:00'), (datetime.time(2, 0), '2:00'), (datetime.time(3, 0), '3:00'), (datetime.time(4, 0), '4:00'), (datetime.time(5, 0), '5:00'), (datetime.time(6, 0), '6:00'), (datetime.time(7, 0), '7:00'), (datetime.time(8, 0), '8:00'), (datetime.time(9, 0), '9:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00'), (datetime.time(23, 0), '23:00')], null=True, verbose_name='Начало рабочего дня'),
        ),
        migrations.AlterField(
            model_name='baseschedule',
            name='week_day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], unique=True, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='doctors.doctor', verbose_name='Доктор'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='end_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(0, 0), '0:00'), (datetime.time(1, 0), '1:00'), (datetime.time(2, 0), '2:00'), (datetime.time(3, 0), '3:00'), (datetime.time(4, 0), '4:00'), (datetime.time(5, 0), '5:00'), (datetime.time(6, 0), '6:00'), (datetime.time(7, 0), '7:00'), (datetime.time(8, 0), '8:00'), (datetime.time(9, 0), '9:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00'), (datetime.time(23, 0), '23:00')], null=True, verbose_name='Конец рабочего дня'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='Работает'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='start_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(0, 0), '0:00'), (datetime.time(1, 0), '1:00'), (datetime.time(2, 0), '2:00'), (datetime.time(3, 0), '3:00'), (datetime.time(4, 0), '4:00'), (datetime.time(5, 0), '5:00'), (datetime.time(6, 0), '6:00'), (datetime.time(7, 0), '7:00'), (datetime.time(8, 0), '8:00'), (datetime.time(9, 0), '9:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00'), (datetime.time(23, 0), '23:00')], null=True, verbose_name='Начало рабочего дня'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='week_day',
            field=models.PositiveBigIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='exceptioncase',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='exceptioncase',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_cases', to='doctors.doctor', verbose_name='Доктор'),
        ),
        migrations.AlterField(
            model_name='exceptioncase',
            name='reason',
            field=models.TextField(max_length=60, verbose_name='Причина'),
        ),
    ]
