# Generated by Django 4.2.14 on 2024-08-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_baseschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseschedule',
            options={'ordering': ('week_day',), 'verbose_name': 'расписание дня клиники', 'verbose_name_plural': 'Расписание клиники'},
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ('doctor', 'week_day'), 'verbose_name': 'расписание дня доктора', 'verbose_name_plural': 'Расписание доктора'},
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='is_working',
        ),
    ]
