# Generated by Django 4.2.14 on 2024-08-20 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_baseschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='end_time',
            field=models.TimeField(choices=[(datetime.time(0, 0), '0:00'), (datetime.time(1, 0), '1:00'), (datetime.time(2, 0), '2:00'), (datetime.time(3, 0), '3:00'), (datetime.time(4, 0), '4:00'), (datetime.time(5, 0), '5:00'), (datetime.time(6, 0), '6:00'), (datetime.time(7, 0), '7:00'), (datetime.time(8, 0), '8:00'), (datetime.time(9, 0), '9:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00'), (datetime.time(23, 0), '23:00')], verbose_name='Конец рабочего дня'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(0, 0), '0:00'), (datetime.time(1, 0), '1:00'), (datetime.time(2, 0), '2:00'), (datetime.time(3, 0), '3:00'), (datetime.time(4, 0), '4:00'), (datetime.time(5, 0), '5:00'), (datetime.time(6, 0), '6:00'), (datetime.time(7, 0), '7:00'), (datetime.time(8, 0), '8:00'), (datetime.time(9, 0), '9:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00'), (datetime.time(23, 0), '23:00')], verbose_name='Начало рабочего дня'),
        ),
    ]
