# Generated by Django 4.2.14 on 2024-08-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_doctorschedule_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptioncase',
            name='reason',
            field=models.TextField(default='Не указано', max_length=60, verbose_name='Причина'),
        ),
    ]
