# Generated by Django 4.2.14 on 2024-08-17 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('time_slots', models.IntegerField(null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrie', to='doctors.doctor', verbose_name='Доктор')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrie', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
                ('service', models.ManyToManyField(to='services.service')),
            ],
            options={
                'verbose_name': 'прием',
                'verbose_name_plural': 'Приемы',
            },
        ),
    ]
