# Generated by Django 4.2.14 on 2024-08-17 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_alter_service_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrie', to='doctors.doctor', verbose_name='Доктор')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrie', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
                ('service', models.ManyToManyField(to='services.service')),
            ],
            options={
                'verbose_name': 'прием',
                'verbose_name_plural': 'Приемы',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала слота')),
                ('entrie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', verbose_name='time_slots')),
            ],
        ),
    ]
